# Generated by Django 4.1.7 on 2023-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pro_favorite',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
