# Generated by Django 4.1.7 on 2023-04-11 01:16

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetails_options_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expire',
            field=creditcards.models.CardExpiryField(default=None),
        ),
        migrations.AddField(
            model_name='payment',
            name='security_code',
            field=creditcards.models.SecurityCodeField(default=None, max_length=4),
        ),
    ]
